[ [ { id: 1,
      google_map_src: 'https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sus!4v1436170635521!6m8!1m7!1sEmPx53PkIOUAAAQqmWhsgw!2m2!1d-36.81214!2d174.726475!3f60.649238235862214!4f-16.318097902715365!5f0.7820865974627469',
      phone_about_content: 'The only Dutch restaurant in New Zealand. It\\u2019s a place where the the Dutch feel at home, and where the Kiwis can explore the delicacies of the low lands. Try our pancakes, poffertjes or a broodje frikandel. Or pick your favourite Dutch Cheese to take home. Choose your restaurant by clicking on the tiles above.',
      phone_about_hoveredIcon: '/demo1/images/icon1.jpg',
      phone_about_icon: '/demo1/images/icon1-bw.jpg',
      phone_about_img: '/demo1/images/hexagon.png',
      phone_about_title: 'ABOUT',
      phone_time_hoveredIcon: '/demo1/images/icon2.jpg',
      phone_time_icon: '/demo1/images/icon2-bw.jpg',
      phone_time_img: '/demo1/images/hexagon.png',
      phone_time_title: 'TIME',
      phone_contact_hoveredIcon: '/demo1/images/icon3.jpg',
      phone_contact_icon: '/demo1/images/icon3-bw.jpg',
      phone_contact_img: '/demo1/images/hexagon.png',
      phone_contact_title: 'CONTACT',
      address: '3-5 Birkenhead ave, Birkenhead, Auckland,',
      phone_en: 'Phone (English): 09 418 1390,',
      phone_cn: 'Phone (中文): 021 022 00379,',
      email: 'Email: info@jibble.co.nz',
      map_address: '3-5 Birkenhead ave, Birkenhead, Auckland',
      map_destination: 'To Dutch Delight:',
      map_start: '3-5 Birkenhead ave, Birkenhead, Auckland',
      name: 'Dutch Delight',
      type: 'Restaurant or Porterhouse',
      introduction: '',
      logo_img: '',
      title_map: '',
      title_gallery: '',
      title_about: '',
      created_at: null,
      updated_at: null } ],
  [ { id: 1,
      image: '/demo1/images/s1.jpg',
      thumb: '/demo1/images/s1.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s1.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 2,
      image: '/demo1/images/s2.jpg',
      thumb: '/demo1/images/s2.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s2.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 3,
      image: '/demo1/images/s3.jpg',
      thumb: '/demo1/images/s3.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s3.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 4,
      image: '/demo1/images/s4.jpg',
      thumb: '/demo1/images/s4.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s4.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 5,
      image: '/demo1/images/s5.jpg',
      thumb: '/demo1/images/s5.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s5.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 6,
      image: '/demo1/images/s6.jpg',
      thumb: '/demo1/images/s6.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s6.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 7,
      image: '/demo1/images/s7.jpg',
      thumb: '/demo1/images/s7.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s7.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 8,
      image: '/demo1/images/s8.jpg',
      thumb: '/demo1/images/s8.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s8.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 9,
      image: '/demo1/images/s9.jpg',
      thumb: '/demo1/images/s9.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s9.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 10,
      image: '/demo1/images/s10.jpg',
      thumb: '/demo1/images/s10.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s10.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 11,
      image: '/demo1/images/s11.jpg',
      thumb: '/demo1/images/s11.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s11.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null },
    { id: 12,
      image: '/demo1/images/s12.jpg',
      thumb: '/demo1/images/s12.jpg',
      title: 'Dutch Delight',
      url: '/demo1/images/s1.jpg',
      customer_id: 1,
      created_at: null,
      updated_at: null } ],
  [ { id: 1,
      display: 'home',
      link: '/home',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 2,
      display: 'gallery',
      link: '/gallery',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 3,
      display: 'phone',
      link: '/phone',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 4,
      display: 'map',
      link: '/map',
      customer_id: '1',
      created_at: null,
      updated_at: null } ],
  [ { id: 1,
      days: 'Today',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 2,
      days: 'Monday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 3,
      days: 'Tuesday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 4,
      days: 'Wednesday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 5,
      days: 'Thursday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 6,
      days: 'Friday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 7,
      days: 'Saturday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null },
    { id: 8,
      days: 'Sunday',
      times: '9:00am - 6:00pm',
      customer_id: '1',
      created_at: null,
      updated_at: null } ] ]
